graph TD
  Greet("IComputed<string> for GreetUserAsync(1)") -->|Depends on| GetUser("IComputed<User> for GetUserAsync(1)")
  Greet("IComputed<string> for GreetUserAsync(1)") -->|Depends on| GetTime("IComputed<DateTime> for GetTimeAsync()")
