classDiagram
  class IComputed {
    +ComputedState State
    +LTag LTag
    +bool IsConsistent
    +TIn Input
    +Result~TOut~ Output
    +TOut Value
    +Exception? Error
    +event~Action~ Invalidated

    +Invalidate()
    +UpdateAsync() ValueTask~IComputed~
    +UseAsync() ValueTask~TOut~
    +WhenInvalidatedAsync() Task
  }
